wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
layer_1_size:
  desc: null
  value: 10
lauyer_2_size:
  desc: null
  value: 20
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690914847.699841
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.10
      5: 0.15.7
      8:
      - 1
      - 5
